apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany  # Multiple pods can mount
  glusterfs:
    endpoints: glusterfs-cluster
    path: thw  # GlusterFS volume name
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
