###
# ```{rubric} Storage Classes Helm Chart
# ```
# ---
# This is the main Helm Chart for the Storage Classes and drivers deployed
# from this repository.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "apiVersion: v2\n"
# :end-before: "###\n"
# ```
apiVersion: v2

###
# ```{rubric} App Version
# ```
# ---
# This is the version number of the application being deployed.
# This version number should be incremented each time you make changes to
# the application. Versions are not expected to follow Semantic Versioning.
# They should reflect the version the application is using.
# It is recommended to use it with quotes.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "appVersion: \"0.5.2\"\n"
# :end-before: "###\n"
# ```
appVersion: "0.5.2"

###
# ```{rubric} Dependencies
# ```
# ---
# A list of chart dependencies.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "dependencies:\n"
# :end-before: "###\n"
# ```
dependencies:
- condition: csi-driver-lvm.enabled
  name: csi-driver-lvm
  repository: https://helm.metal-stack.io
  version: ~0.6
- condition: local-static-provisioner.enabled
  name: local-static-provisioner
  repository: file://./local-static-provisioner/
  version: ~2

###
# ```{rubric} Description
# ```
# ---
# A brief description of the current chart.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "description: A Helm chart to deploy local StorageClasses\n"
# :end-before: "###\n"
# ```
description: A Helm chart to deploy local StorageClasses

###
# ```{rubric} Icon
# ```
# ---
# A url or file path to the Chart's icon.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "icon: https://edwardtheharris.github.io/helm-storage-classes/_static/StorageClasses.png\n"
# :end-before: "###\n"
# ```
icon: https://edwardtheharris.github.io/helm-storage-classes/_static/StorageClasses.png

###
# ```{rubric} Name
# ```
# ---
# The name of the chart.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "name: lvm\n"
# :end-before: "###\n"
# ```
name: lvm

###
# ```{rubric} Type
# ```
# ---
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer.
# They're included as a dependency of application charts to inject those
# utilities and functions into the rendering pipeline. Library charts do not
# define any templates and therefore cannot be deployed.
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "type: application\n"
# :end-before: "###\n"
# ```
type: application

###
# ```{rubric} Chart Version
# ```
# ---
# This is the chart version. This version number should be incremented each
# time you make changes to the chart and its templates, including the app
# version. Versions are expected to follow Semantic
# [Versioning](https://semver.org/)
#
# ```{literalinclude} /Chart.yaml
# :language: yaml
# :start-at: "version: 0.0.3\n"
# ```
version: 0.0.3
