---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.lvm.driverName }}
  labels:
    {{- include "csi-driver-lvm.labels" . | nindent 4 }}
spec:
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  podInfoOnMount: true
  attachRequired: false
