{{- range .Values.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .name }}"
  annotations:
    storage.kubernetes.io/capacity: {{ .capacity }}
    storage.kubernetes.io/class: {{ .class }}
    storage.kubernetes.io/hostname: {{ .hostname }}
  labels:
    storage.kubernetes.io/node: {{ .hostname }}
spec:
  capacity:
    storage: {{ .capacity }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .class }}
  local:
    path: "/mnt/{{ .class }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .hostname }}
{{- end }}
