---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  {{- with .Values.hdd }}
    storageclass.kubernetes.io/is-default-class: {{ .default }}
    storageclass.kubernetes.io/name: {{ .name }}
    storageclass.kubernetes.io/provisioner: {{ .provisioner }}
    storageclass.kubernetes.io/type: {{ .type }}
  name: {{ .name | quote }}
  {{- end }}
  {{- with .Values.local }}
    storageclass.kubernetes.io/name: {{ .name }}
    storageclass.kubernetes.io/provisioner: {{ .provisioner }}
    storageclass.kubernetes.io/type: {{ .type }}
  name: {{ .name }}
  {{- end }}
  {{- with .Values.usb }}
    storageclass.kubernetes.io/name: {{ .name }}
    storageclass.kubernetes.io/provisioner: {{ .provisioner }}
    storageclass.kubernetes.io/type: {{ .type }}
  name: {{ .name }}
  {{- end }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
