{{ if ".Values.csi-driver-lvm.storageClasses.linear.enabled" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-linear-btrfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/name: csi-lvm
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
  fsType: btrfs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-linear
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/name: csi-lvm
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: linear
{{ end }}
{{ if ".Values.csi-driver-lvm.storageClasses.mirror.enabled" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-mirror
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    storageclass.kubernetes.io/raid: "1"
  labels:
    app.kubernetes.io/name: csi-lvm
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: mirror
{{ end }}
{{ if ".Values.csi-driver-lvm.storageClasses.striped.enabled" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-striped
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    storageclass.kubernetes.io/raid: "0"
  labels:
    app.kubernetes.io/name: csi-lvm
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "striped"
{{ end }}
