<<<<<<< Updated upstream
{{ if .Values.lvm.storageClasses.btrfs.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.lvm.storageClasses.btrfs.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: {{ .Values.lvm.storageClasses.linear.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
  fsType: btrfs
{{ end }}
{{ if .Values.lvm.storageClasses.linear.enabled }}
---
=======
{{ if ".Values.csi-lvm.storageClasses.linear.enabled" }}
>>>>>>> Stashed changes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.lvm.storageClasses.linear.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
<<<<<<< Updated upstream
reclaimPolicy: {{ .Values.lvm.storageClasses.linear.reclaimPolicy }}
=======
reclaimPolicy: Delete
>>>>>>> Stashed changes
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
  fsType: btrfs
{{ end }}
<<<<<<< Updated upstream
{{ if .Values.lvm.storageClasses.mirror.enabled }}
=======
{{ if ".Values.csi-lvm.storageClasses.mirror.enabled" }}
>>>>>>> Stashed changes
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-mirror
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    storageclass.kubernetes.io/raid: "1"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
allowVolumeExpansion: true
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: {{ .Values.lvm.storageClasses.mirror.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: mirror
{{ end }}
<<<<<<< Updated upstream
{{ if .Values.lvm.storageClasses.striped.enabled }}
=======
{{ if ".Values.csi-lvm.storageClasses.striped.enabled" }}
>>>>>>> Stashed changes
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-striped
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    storageclass.kubernetes.io/raid: "0"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: {{ .Values.lvm.storageClasses.striped.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "striped"
{{ end }}
