---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-driver-lvm-pod-test
  namespace: csi-driver-lvm
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/name: csi-driver-lvm-pod-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-driver-lvm-linear
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-driver-lvm-pod-test
  namespace: csi-driver-lvm
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: hook-succeeded
    app.kubernetes.io/name: csi-driver-lvm-pod-test
  labels:
    name: csi-driver-lvm-pod-test
    app.kubernetes.io/name: csi-driver-lvm-pod-test
spec:
  restartPolicy: Never
  containers:
    - image: dandb79/lsblk-testing:v1.2
      command: ["lsblk"]
      name: csi-driver-lvm-pod-test
      volumeMounts:
        - name: lvm
          mountPath: /data
  nodeSelector:
    kubernetes.io/os: linux
  volumes:
    - name: lvm
      persistentVolumeClaim:
        claimName: csi-driver-lvm-pod-test
