apiVersion: v1
appVersion: v0.5.2
description: local persistend storage for lvm
home: https://metal-stack.io
keywords:
- storage
- block-storage
- volume
name: csi-driver-lvm
sources:
- https://github.com/metal-stack
version: 0.6.0
