###
# ```{rubric} CSI Driver LVM values
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "lvm:\n"
# :end-before: "###\n"
# ```
lvm:
  # This one you
  # should change
  devicePattern: /dev/nvme[0-9]n[0-9]

  # You will want to change this
  # for read-only filesystems
  # For example, in Talos OS, set
  # this to `/var/etc/lvm`
  hostWritePath: /etc/lvm

  # these are primariliy for testing purposes
  vgName: csi-lvm
  driverName: lvm.csi.metal-stack.io
  storageClassStub: csi-driver-lvm

###
# ```{rubric} Role Based Access Control
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "rbac:\n"
# :end-before: "###\n"
# ```
rbac:
  create: true
  pspEnabled: true

###
# ```{rubric} Backwards Compatability
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "compat03x: false\n"
# :end-before: "###\n"
# ```
#
# enable, if you want to install storage classes with
# v0.3.x backward-compatible `csi-lvm-sc-*` names
compat03x: false

###
# ```{rubric} CSI Driver Plugin Image
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "pluginImage:\n"
# :end-before: "###\n"
# ```
pluginImage:
  repository: ghcr.io/metal-stack/csi-driver-lvm
  tag: v0.5.2
  pullPolicy: IfNotPresent

###
# ```{rubric} CSI Driver Provisioner Image
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "provisionerImage:\n"
# :end-before: "###\n"
# ```
provisionerImage:
  repository: ghcr.io/metal-stack/csi-driver-lvm-provisioner
  tag: v0.5.2
  pullPolicy: IfNotPresent

###
# ```{rubric} Kubernetes
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "kubernetes:\n"
# :end-before: "###\n"
# ```
kubernetes:
  kubeletPath: /var/lib/kubelet

###
# ```{rubric} Storage Classes
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "storageClasses:\n"
# :end-before: "###\n"
# ```
storageClasses:
  linear:
    enabled: true
    additionalAnnotations: []
    # this might be used to mark one of the StorageClasses as default:
    # storageclass.kubernetes.io/is-default-class: "true"
    reclaimPolicy: Delete
  striped:
    enabled: true
    additionalAnnotations: []
    reclaimPolicy: Delete
  mirror:
    enabled: true
    additionalAnnotations: []
    reclaimPolicy: Delete

###
# ```{rubric} Custom CSI Sidecars
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "pluginImage:\n"
# :end-before: "###\n"
# ```
#
# uncomment and set these if enabled=true
#
# ```{code-block} yaml
# attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0
# livenessprobe: k8s.gcr.io/sig-storage/livenessprobe:v2.7.0
# provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.2.1
# registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
# resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.6.0
# ```
customCSISidecars:
  enabled: false

  attacher: ''
  livenessprobe: ''
  provisioner: ''
  registrar: ''
  resizer: ''

###
# ```{rubric} Node Selector
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "nodeSelector:\n"
# :end-before: "###\n"
# ```
nodeSelector:
  # The plugin daemonset will run on all nodes if it has a toleration,
  # so it is not necessary to set a nodeSelector for it

  plugin: {}
  # node-role.kubernetes.io/master: ""
  # Key name may need to be updated to 'node-role.kubernetes.io/control-plane'
  # in the future

  # The provisioner has an affinity for nodes with a plugin pod,
  # but since that's a daemonset, we allow more fine-grained node selection

  provisioner: {}
  # node-role.kubernetes.io/master: ""
  # Key name may need to be updated to 'node-role.kubernetes.io/control-plane'
  # in the future

###
# ```{rubric} Tolerations
# ```
# ---
# Default values for the chart.
#
# ```{literalinclude} /charts/csi-driver-lvm/values.yaml
# :caption: default values
# :language: yaml
# :start-at: "tolerations:\n"
# ```
#
# ```{code-block} yaml
#   plugin:
#   - key: node-role.kubernetes.io/master
#     operator: Exists
#     effect: NoSchedule
#   - key: node-role.kubernetes.io/control-plane
#     operator: Exists
#     effect: NoSchedule
#  provisioner:
#   - key: node-role.kubernetes.io/master
#     operator: Exists
#     effect: NoSchedule
#   - key: node-role.kubernetes.io/control-plane
#     operator: Exists
#     effect: NoSchedule
# ```
tolerations:
  plugin: []
  provisioner: []
