name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
            fetch-depth: 0
      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0
        with:
            version: "v3.15.3"
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Add namespace
        run: kubectl create ns csi-driver-lvm
      - name: Add metal stack repo
        run: helm repo add lvm https://helm.metal-stack.io
      - name: Update dependencies
        run: helm dependency update
      - name: Build dependencies
        run: helm dependency build
      - name: Install chart
        run: |
          helm -n csi-driver-lvm upgrade --install lvm -f values.yaml .
          helm -n csi-driver-lvm list
      - name: Test chart
        run: helm -n csi-driver-lvm test lvm
